### ISSUE TITLE
Showing ARC Semantic issue

### ISSUE THREAD

**Issue by darkhorse-coder** [gscarrone/iOS-QR-Code-Generator#1]
Hi there.
I have got below issue when i import QRCodeGenerator.h in my viewcontroller.h file.

QRCodeGenerator/CIColor+QRCode.m:38:45: No known class method for selector 'getSafeString:'

[https://d.pr/i/hAdooN](url)

How can i use this library in my viewcontroller?
Thanks in advance.

**Comment by ghost** [comment]
You have to disable ARC for both QR-Code-Generator classes.

In your project 

> Build Phases -> Compile sources

add `-fno-objc-arc` flag to `QRCodeGenerator.m` and `CIColor+QRCode.m.`

If you need to know more about arc and how to disable it: https://stackoverflow.com/questions/6646052/how-can-i-disable-arc-for-a-single-file-in-a-project

**Comment by gscarrone** [comment]
I will fix this week. No needed to disable ARC

**Comment by gscarrone** [comment]
Added missing NSString Category. Now it works. No needed to disable ARC
